### ISSUE TITLE
Research hosting options for backend

### ISSUE THREAD

**Issue by sim1029** [PennAppsDreamTeam/pennapps-2023#3]

**Comment by Lin-Gene** [comment]
AWS?

**Comment by sim1029** [comment]
Gunna try to get GCP code runner working if they ever give me the credits for it. Gunna need to dockerize the application though which I will do shortly

**Comment by sim1029** [comment]
Gunna close this and open new issues for the dockerization/GCP hosting on cloud runner see:

https://github.com/sekR4/FastAPI-on-Google-Cloud-Run
